# Generated by Django 5.2.14 on 2026-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_salary_employee_employee_salary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.IntegerField(default=0),
        ),
    ]
