# Generated by Django 5.2.14 on 2026-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_role_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
